### ISSUE TITLE
Change "vizgr" response from XML to JSON

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/date-info#5]
`Vizgr` API currrently gives XML response, it should be changed to JSON to keep uniformity across code
Reference: http://www.vizgr.org/historical-events/

**Comment by iwex** [comment]
I'll take it

**Comment by iwex** [comment]
I think there is no sense to do it because vizgr returns invalid JSON (they have multiple `event` keys in one object)

**Comment by prabhakar267** [comment]
@iwex I checked JSON response from API
Closing the issue, since they have an invalid JSON response as of now

**Comment by iwex** [comment]
Please, create new hacktoberfest issue and i'll refactor your code)
